spring.application.name=Spring_social_youtube


#spring.datasource.url=jdbc:mysql://localhost:3306/socialmedia
#spring.datasource.username=root
#spring.datasource.password=Ajay@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.show-sql: true
#spring.jpa.hibernate.ddl-auto=update

##spring.security.user.name=admin
##spring.security.user.password=12345


#
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://ep-orange-field-a1n03qmq.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tm4bjJlDeX7y
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update